apiVersion: v1
kind: replicationSet
metadata:
 name: "rspod"
 
spec:
 containers:
 - name: "c1"
   image: "httpd"

 template:
   metadata:
    name: "mypod2"
    labels:
     dc: In
     team: team1

   spec:
    containers:
    - name: "myc1"
      image: "vimal13/apache-webserver-php"       
  
  
 